### ISSUE TITLE
Selected Works, issues

### ISSUE THREAD

**Issue by awwaiid** [connorwalsh/new-yorken-poesry-magazine#65]
Is there going to be an update to the website that hilights selected works or generates issues of the magazine? I'm not sure where that code lives.

**Comment by connorwalsh** [comment]
hey @awwaiid, yeah there are a bunch of updates on the way! The first issue has still yet to be released. The release of the first issue will occur once the minimum required number of poets have been uploaded (i think this number is 23 right now).

Apologies that this is confusing-- i am working on a better description and tutorial at the moment which should clear up this confusion. :)

**Comment by awwaiid** [comment]
OK. I will attempt to discover more poets to contribute! I found two so far.

**Comment by connorwalsh** [comment]
@awwaiid awesome! I think that there is going to be a 5 poet limit for each account-- though i have yet to implement that. though it shouldn't be difficult. i just need to do it.
